---
abstract: "Perl extension for blah blah blah"
author:
  - A. U. Thor, a.u.thor@a.galaxy.far.far.away
build_requires:
  Module::Build::Tiny: '0'
test_requires:
  Test::Deep: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Strange
no_index:
  directory:
    - t
    - inc
resources:
  repository: http://github.com/a.u.thor/Strange
  bugtracker: http://github.com/a.u.thor/Strange/issues/
version: 2.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
